"""add description to categories

Revision ID: 3dee629b7f69
Revises: 9d9a5d2c7f01
Create Date: 2026-09-26 12:22:52.766912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dee629b7f69'
down_revision: Union[str, None] = '9d9a5d2c7f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
