"""initial schema

Revision ID: 7124a8bba890
Revises: 
Create Date: 2026-09-26 11:24:12.355089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7124a8bba890'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING', 'READY', 'DONE', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('responsible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('receive_from', sa.String(length=255), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'DONE', 'CANCELLED', name='receiptstatus'), nullable=False),
    sa.Column('responsible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('delivery_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('on_hand_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_product_location')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DONE', 'CANCELLED', name='adjustmentstatus'), nullable=False),
    sa.Column('responsible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('stock_moves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('move_type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='movetype'), nullable=False),
    sa.Column('source_type', sa.Enum('RECEIPT', 'DELIVERY', 'TRANSFER', 'ADJUSTMENT', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustment_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adjustment_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('old_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('new_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_id'], ['stock_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_adjustment_items')
    op.drop_table('stock_moves')
    op.drop_table('stock_adjustments')
    op.drop_table('stock')
    op.drop_table('receipt_items')
    op.drop_table('delivery_items')
    op.drop_table('receipts')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_table('deliveries')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
